os:
- linux
services:
- docker
language: node_js
node_js:
- 6.10.3
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - node
  - node_modules
  - "$HOME/.m2"
  - "$HOME/.yarn-cache"
env:
  global:
  - NODE_VERSION=6.10.3
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
before_install:
- jdk_switcher use oraclejdk8
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install
script:
- chmod +x mvnw
- "./mvnw clean test"
- yarn test
- "./mvnw package -Pprod -DskipTests"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
deploy:
  edge: true
  provider: bluemixcloudfoundry
  manifest: ./deploy/cloudfoundry/manifest.yml
  api: https://api.ng.bluemix.net
  username: yohan.ginon@eiosis.com
  password:
    secure: owk6+5V5oFFFGOqtN/gIFMh+a7TU6pRKlU15RVDLyghdPn+pvoiQ2nGvr3oNlXKZCSql+GT59zOrno4unBvmpWJEoHK355lhFW368VcsrZPCKRAVl2csP7FA7lF+SQ0Gduuk3AowwIBSSwWd0bwSWdOsRI38FuiWyWOVR1cJabetOzsndJUjlp0ZmL4Tq1hVpeG3eVQuNOCuDCEGissua3THohHBULhSAFW1eW9GK+78ljEzOg/QmK4Dm9vvSLP0cSECHAY5t0WcU5erADlNKkTrvT8mCoo889BrItsqeYwK4eFg/gyCzSduoshBP0G9kzUJs6+Q9tDY6G81gJ11ubt2aVGUKw/juhsi0dtxyd+AdACX0yqsZZGsog/ac3cSwghfotWPGgCFRr+imO74ooyxDtW9LCIAY41lvudotN8RNOuCzWG2MJOsnYYolgT6okv/+ZAfj8j2/qUo6GqOSdyuDWhGpF1JljLf+mQB7qHK0wwVLebHmlvS4kmJ6x2PLqm6Hlkfg/8M/ogCOUZSJfHyjySw6XqtMJwnwOp+xukmA/w9GtZJcBMUi+gLYC05rYzRDavFx78UMJzVw0stq7Msbtj7UUJfKCI7JyrCvsqeHWjJad/Trfrf/oKDoD1/FYqKdNBurJVIf3K2uS4eIuZP3ZMK9/aUWwP3YkAIlu0=
  organization: SlateDigital
  space: dev
  on:
    repo: yohan-ginon/slatedigital
