version: '2'
services:
    slate-app:
        image: slate
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://slate-postgresql:5432/slate
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    slate-postgresql:
        extends:
            file: postgresql.yml
            service: slate-postgresql
